name: Sync with template

on:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      workflows: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Template Changes
        uses: AndreasAugustin/actions-template-sync@v1.1.8
        with:
          github_token: ${{ secrets.SCORE_BOT_PAT}}
          source_repo_path: "eclipse-score/module_template"
          upstream_branch: "main"
          pr_title: "[Template Sync] Upstream template update"
          pr_commit_msg: "chore(template): upstream template update"
